### ISSUE TITLE
[BUG] 无法重新编辑文章

### ISSUE THREAD

**Issue by easilylazy** [Monkey-Mouse/mo2#296]
**描述你遇到的bug**
在发布文章后，重新点击编辑按钮，页面加载不出来

**复现bug**
复现bug的步骤
1. 打开文章页面
2. 点击 编辑 按钮
3. 发生错误

**期待结果**
详细描述应该发生什么

**截图**
![image](https://user-images.githubusercontent.com/47478961/125734940-8a116f98-9d3b-4bf4-b01c-d7546580a875.png)

**Comment by Chronostasys** [comment]
fixed with #295
